#%RAML 1.0 DataType
type: object
properties:
  id?: number
  userName: string
  email:
    type: string
    pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$
    example: "romelherreratgk@gmail.com"      
  name: string
  lastname: string
  password?: string