#%RAML 1.0
title: rom-prueba-mulesoft-sys-api
version: v1
baseUri: http://rom-prueba-mulesoft-sys-api/api/v1

types:
  User: !include datatypes/user.raml
  Message: !include datatypes/message.raml
  Album: !include datatypes/album.raml

securitySchemes:
  oauth_2_0:
        description: |
            Mule OAuth 2.0.
        type: OAuth 2.0
        describedBy:
            headers:
                Authorization:
                    description: |
                      Used to send a valid OAuth 2 access token. Do not use
                      with the "access_token" query string parameter.
                    type: string
                        
            responses:
                401:
                    description: |
                        Bad or expired token.
                403:
                    description: |
                        Bad OAuth request.
        settings:
          authorizationUri: http://0.0.0.0:8081/authorize
          accessTokenUri: http://0.0.0.0:8081/access-token
          authorizationGrants: [authorization_code, password, client_credentials, implicit]

/users:
  get:
    securedBy: [oauth_2_0]
    description: "Get all users"
    displayName: "Get Users"
    responses:
      200:
        headers:
          content-type:
            example: "application/json"
        body:
          application/json:
            type: User[]
            example: !include examples/all-users.json

  /{id}:
    description: A specific User by ID
    uriParameters:
     id:
       description: A specific User by ID
       type: integer
       example: 1
    get:
      securedBy: [oauth_2_0]
      description: "Get User by ID"
      displayName: "Get User by ID"
      responses:
        200:
          headers:
            content-type:
              example: "application/json"
          body:
            application/json:
              type: User
              example: !include examples/user-by-id.json

  post:
    securedBy: [oauth_2_0]
    description: "Create a new User"
    displayName: "Create User"
    body:
      application/json:
        type: User
        example: !include examples/request-new-user.json
    responses:
      201:
        headers:
          content-type:
            example: "application/json"
        body:
          application/json:
            type: Message
            example: !include examples/response-new-user.json

/albums:
  get:
    securedBy: [oauth_2_0]
    description: "Get all albums"
    displayName: "Get Albums"
    responses:
      200:
        headers:
          content-type:
            example: "application/json"
        body:
          application/json:
            type: Album[]
            example: !include examples/all-albums.json
              
              


